import { CameraComponent, Datalist, FileUploadComponent } from "@/pages/Login";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title> Optical character recognition </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Login /> */}
      <div className="  flex flex-col items-center justify-center">
        <CameraComponent />

        <div className="space-y-20">
          <h1 className="text-2xl">
            Upload File <strong>Or</strong> Take a picture
          </h1>
          <FileUploadComponent />
        </div>

        <Datalist />
      </div>
    </div>
  );
}
