import { IbanForm } from "@/Components/Form";
import { Navbar } from "@/Components/Navbar";
import Table from "@/Components/Table";
import {
  CameraComponent,
  Datalist,
  FileUploadComponent,
  Login,
} from "@/pages/Login";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [user, setUser] = useState(false);
  useEffect(() => {
    console.log("render");
  }, [user]);
  return (
    <div>
      <Navbar user={user} setUser={setUser} />
      <Head>
        <title> Optical character recognition </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!user && <Login setUser={setUser} />}
      {user && (
        <div className="  flex flex-col items-center justify-center">
          <IbanForm />
          <CameraComponent />

          <div className="space-y-20 px-3 py-2">
            <h1 className="text-center text-2xl">
              Upload <strong className="text-blue-400"> Or </strong> Take a
              picture
            </h1>
            <FileUploadComponent />
          </div>
          <Table />
        </div>
      )}
    </div>
  );
}
