import { Navbar } from "@/Components/Navbar";
import { CameraComponent, Datalist, FileUploadComponent, Login } from "@/pages/Login";
import Head from "next/head";
import { useState } from "react";



export default function Home() {
  const [user, setUser] = useState(false)
  return (
    <div>

      <Navbar  user={user}/>
      <Head>
        <title> Optical character recognition </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login setUser={setUser} />
      <div className="  flex flex-col items-center justify-center">
        {/* <CameraComponent /> */}

        <div className="space-y-20 p-4">
          <h1 className="text-center text-2xl">
            Upload File <strong className="text-blue-400">Or</strong> Take a
            picture
          </h1>
          <FileUploadComponent />
        </div>

        <Datalist />
      </div>
    </div>
  );
}
